CREATE TABLE Passengers(
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    age INT NOT NULL
);

INSERT INTO Passengers VALUES("Amelia","Earhart",39);

CREATE TABLE "Check-Ins"(
    DATE_TIME DATETIME,
    FLIGHT TEXT NOT NULL
);

INSERT INTO "Check-Ins" VALUES("2023-08-03 15:03","Delta Flight 300");

CREATE TABLE Airlines(
    NAME TEXT NOT NULL,
    "CONCOURSE" TEXT NOT NULL Check ("CONCOURSE" IN ('A','B','C','D','E','F','T'))
);


INSERT INTO AIRLINES VALUES("Delta","A");
INSERT INTO AIRLINES VALUES("Delta","B");
INSERT INTO AIRLINES VALUES("Delta","C");
INSERT INTO AIRLINES VALUES("Delta","D");
INSERT INTO AIRLINES VALUES("Delta","T");

CREATE TABLE Flights(
    FLIGHT_NUMBER INT NOT NULL,
    AIRLINE_NAME TEXT NOT NULL,
    DEP_CODE TEXT NOT NULL CHECK(DEP_CODE IN ('ATL','BOS')),
    ARRIVE_CODE TEXT NOT NULL CHECK(ARRIVE_CODE IN ('ATL','BOS')),
    DEP_DATETIME DATETIME,
    ARRIVE_DATETIME DATETIME,
    PRIMARY KEY(FLIGHT_NUMBER)
);

INSERT INTO Flights VALUES(900,"Delta","ATL","BOS","2023-08-03 18:46" , "2023-08-03 21:09");
